from pathlib import Path
from html import escape
import shutil
import re
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / 'content.txt'
lines = [x.strip() for x in SOURCE.read_text(encoding='utf-8-sig').splitlines() if x.strip()]
FORM = 'https://form.respondi.app/n3RiRFmz'
def txt(prefix):
    return escape(next(x for x in lines if x.startswith(prefix)))
def p(prefix, cls=''):
    return f'<p class="{cls}">{txt(prefix)}</p>'
def title(kicker, prefix):
    return f'<span class="eyebrow">{escape(kicker)}</span><h2>{txt(prefix)}</h2>'
def button(label='Aplicar para o PAC'):
    return f'<a class="button-glow" href="{FORM}" target="_blank" rel="noopener noreferrer">{label}<span aria-hidden="true">↗</span></a>'
def listing(items):
    return '<ul class="checks">'+''.join(f'<li>{txt(x)}</li>' for x in items)+'</ul>'
def card(n, name, prefix):
    return f'<article class="home-grid-box-wrapper"><div class="home-grid-box pac-card"><span class="number">{n}</span><h3>{name}</h3>{p(prefix)}</div></article>'

hero = f'''<header class="pac-nav"><div class="wrap nav-inner"><a class="pac-brand" href="#inicio" aria-label="PAC / Legacy Doctors — início"><span class="brand-mark">P</span><span>PAC <span class="brand-divider">/</span> <small>Legacy Doctors</small></span></a><nav aria-label="Menu principal"><a href="#pilares">Pilares</a><a href="#experiencia">Experiência</a><a href="#selecao">Seleção</a><a href="#faq">FAQ</a></nav>{button()}</div></header>
<main id="inicio"><section class="pac-hero"><div class="wrap hero-copy"><div class="ease-badge"><span class="whats-new">Imersão presencial gratuita</span><span>Até 30 médicos · Londrina/PR</span></div><p class="eyebrow program">PAC — Programa de Aceleração de Clínicas</p><h1 class="hero-title">Agenda cheia não significa<br><span>clínica lucrativa.</span></h1>{p('Descubra o que','hero-lead')}{p('Uma imersão presencial de 2','hero-description')}<div class="hero-button-holder"><a class="button-simple" href="#sobre">Conheça o PAC <span aria-hidden="true">↓</span></a>{button()}</div></div><div class="pac-orbit" aria-hidden="true"><img src="images/673c8790c213543ea74788a0_Red%20Circle%20No%20Glow-p-1080.png" alt=""><img class="orbit-glow" src="images/673c87ad03ca3526725241f9_Red%20Glow-p-1080.png" alt=""></div><div class="wrap stats-wrap"><div class="stats home-grid-box-wrapper"><div><strong>2 dias</strong><span>Presenciais</span></div><div><strong>Londrina</strong><span>Paraná</span></div><div><strong>Até 30</strong><span>Médicos</span></div><div><strong>Gratuita</strong><span>Mediante aplicação</span></div></div></div></section>'''

body = f'''<section class="section-pad wrap" id="sobre"><div class="split"><div>{title('Quebra de crença','Se sua agenda está cheia, mas')}</div><div class="section-prose">{p('Muitos médicos tentam')}{p('Mas crescimento de volume','emphasis')}</div></div><div class="feature-panel split"><div>{title('O que é o PAC','Dois dias para olhar')}{p('Uma imersão presencial criada')}</div><div class="pill-cloud">{''.join('<span>'+x+'</span>' for x in ['Gestão','Posicionamento','Precificação','Marketing','Vendas','Processos','Estrutura comercial','Crescimento'])}</div></div></section>
<section class="section-pad wrap"><div class="split"><div>{title('Para quem é','Excelência técnica')}{p('Uma experiência para médicos','subtle')}</div><div>{listing(['Médicos donos de clínica','Profissionais em fase','Médicos com demanda','Clínicas sem processo','Profissionais que querem','Médicos que desejam'])}</div></div></section>
<section class="section-pad wrap"><div class="section-heading">{title('Volume versus margem','Atender mais não')}</div><div class="comparison"><div class="feature-panel"><h3>O ciclo que aumenta complexidade</h3><ol class="cycle">{''.join(f'<li><span>0{i+1}</span>{x}</li>' for i,x in enumerate(['Mais pacientes','Mais trabalho','Mais equipe','Mais custos','Mais complexidade']))}</ol></div><div class="feature-panel efficient"><span class="eyebrow">Uma lógica mais eficiente</span><h3 class="formula">Posicionamento <b>+</b> Precificação <b>+</b> Processo comercial <b>+</b> Gestão</h3><p class="emphasis">Crescimento com maior eficiência.</p>{p('Uma direção estratégica','subtle')}</div></div></section>
<section class="section-pad wrap" id="pilares"><div class="section-heading">{title('Os cinco pilares','As alavancas que')}</div><div class="pillar-grid">{card('01','Precificação','Saia da lógica')}{card('02','Posicionamento','Construa uma percepção')}{card('03','Vendas','Estruture um processo')}{card('04','Gestão','Organize a operação')}{card('05','Estrutura para escala','Identifique gargalos')}</div></section>
<section class="section-pad wrap" id="experiencia"><div class="experience feature-panel"><div><span class="eyebrow">Imersão presencial</span><div class="experience-number">2<span>dias</span></div><p>Londrina/PR</p></div><div>{title('Durante os dois dias','Profundidade, discussão')}{p('Os participantes aprofundarão')}{listing(['Precificação e posicionamento','Processo comercial e vendas','Gestão, indicadores e equipe','Processos, crescimento e escala'])}</div></div></section>
<section class="section-pad wrap"><div class="split"><div><span class="eyebrow">Resultados e provas</span><div class="result-number">+200%</div>{p('de aumento no ticket','emphasis')}{p('Os resultados apresentados','subtle')}</div><div class="proof-list">{''.join('<div><h3>'+x+'</h3><span class="subtle">Material em atualização</span></div>' for x in ['Depoimentos em vídeo','Histórias de médicos','Cases da metodologia','Resultados específicos'])}</div></div></section>
<section class="section-pad wrap"><div class="split"><div>{title('Quem conduz','Com Dr. Daniel')}{p('A imersão será conduzida')}{p('Trajetória profissional','subtle')}</div><div class="feature-panel legacy"><span class="eyebrow">Ecossistema</span><h3>LEGACY<br><span>DOCTORS</span></h3>{p('O PAC faz parte')}</div></div></section>
<section class="section-pad wrap" id="selecao"><div class="split"><div>{title('Curadoria','O PAC não será')}{p('Esta edição será limitada')}{listing(['Não é venda','Não é inscrição','A aplicação não garante','Existe um processo'])}</div><div class="feature-panel"><span class="eyebrow">Por que a participação é gratuita</span><h3>Uma edição piloto.<br>Sem cobrança de ingresso.</h3>{p('Nesta edição piloto')}{p('Transporte, hospedagem','subtle')}</div></div><div class="section-heading spaced">{title('Como funciona','Uma seleção em três')}</div><div class="steps">{card('01','Aplique','Preencha o formulário')}{card('02','Análise','A equipe analisará')}{card('03','Seleção','Os médicos mais alinhados')}</div><p class="subtle centered">O preenchimento da aplicação não garante participação.</p></section>
<section class="section-pad wrap" id="aplicacao"><div class="application feature-panel"><div>{title('Aplicação','Aplicar para o PAC.')}{p('Preencha suas informações')}{listing(['Sem cobrança de ingresso','Sem compromisso de compra','Sem solicitação de faturamento'])}</div><div class="apply-action"><p class="emphasis">Nome completo · WhatsApp · Cidade / UF<br>Instagram · Especialidade médica</p>{button('Preencher aplicação')}{p('Após o envio','subtle')}</div></div></section>
<section class="section-pad wrap"><div class="split"><div>{title('Informações práticas','Uma experiência presencial e concentrada.')}</div><dl class="practical">{''.join(f'<div><dt>{k}</dt><dd>{v}</dd></div>' for k,v in [('Programa','PAC — Aceleração de Clínicas'),('Formato','Presencial'),('Duração','2 dias'),('Local','Londrina/PR'),('Vagas','Até 30 médicos'),('Condução','Dr. Daniel Botelho'),('Ecossistema','Legacy Doctors'),('Participação','Gratuita para selecionados'),('Entrada','Mediante aplicação'),('Data','A definir')])}</dl></div></section>
<section class="section-pad wrap" id="faq"><div class="split"><div>{title('FAQ','Perguntas frequentes.')}</div><div class="faq-list">'''
faqs=[('O PAC é gratuito?','Nesta edição piloto, não haverá cobrança de ingresso. Os médicos selecionados poderão participar sem custo de inscrição. Transporte, hospedagem, alimentação e demais despesas não estão confirmados como inclusos.'),('Qualquer médico pode participar?','O PAC é voltado a médicos donos de clínicas e cirurgiões plásticos. Cada aplicação será analisada, e serão selecionados os profissionais mais alinhados ao momento e à proposta da experiência.'),('Preencher o formulário garante uma vaga?','Não. O preenchimento da aplicação é a primeira etapa do processo de seleção e não garante participação.'),('Quantos médicos serão selecionados?','Esta edição será limitada a até 30 médicos.'),('Onde acontecerá?','Em Londrina, no Paraná. A data está a definir.'),('Quanto tempo dura?','A imersão tem duração de 2 dias presenciais.'),('Quem conduz o programa?','Dr. Daniel Botelho, em uma iniciativa do ecossistema Legacy Doctors.'),('Preciso informar meu faturamento?','Não há solicitação de faturamento nesta etapa da aplicação.')]
body += ''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>' for q,a in faqs)
body += f'''</div></div></section><section class="section-pad wrap final-cta"><span class="eyebrow">Próximo passo</span><h2>{txt('Se sua agenda já está')}</h2>{p('Pode ser estruturar')}{p('O PAC reunirá')}{button()}<p class="subtle">As vagas são limitadas e a participação dependerá da análise e seleção do perfil.</p></section></main><footer class="wrap"><a class="pac-brand" href="#inicio"><span class="brand-mark">P</span><span>PAC <span class="brand-divider">/</span> <small>Legacy Doctors</small></span></a><p>PAC — Programa de Aceleração de Clínicas<br><span class="subtle">Uma iniciativa do ecossistema Legacy Doctors.</span></p><a href="#inicio">Voltar ao início ↑</a></footer>'''
head='''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>PAC — Programa de Aceleração de Clínicas | Legacy Doctors</title><meta name="description" content="Imersão presencial gratuita de 2 dias em Londrina para até 30 médicos. Precificação, posicionamento, vendas e gestão para clínicas. Participação mediante seleção."><meta property="og:title" content="PAC — Programa de Aceleração de Clínicas"><meta property="og:description" content="Agenda cheia não significa clínica lucrativa. Dois dias presenciais em Londrina com Dr. Daniel Botelho."><meta property="og:type" content="website"><link rel="icon" href="images/pac-favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Mulish:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/ovo-redsun.webflow.85f609341.css"><link rel="stylesheet" href="css/pac.css"></head><body><a class="skip-link" href="#sobre">Pular para o conteúdo</a>'''
(ROOT/'index.html').write_text(head+hero+body+'</body></html>',encoding='utf-8')
(ROOT/'images/pac-favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#f66f14"/><text x="11" y="29" fill="white" font-family="Arial" font-size="28" font-weight="bold">P</text></svg>',encoding='utf-8')
dist=ROOT/'dist'
dist.mkdir(exist_ok=True)
shutil.copy2(ROOT/'index.html',dist/'index.html')
for folder in ['css','images']:
    shutil.copytree(ROOT/folder,dist/folder,dirs_exist_ok=True)
html=(ROOT/'index.html').read_text(encoding='utf-8')
for ref in re.findall(r'(?:src|href)="([^"#]+)"',html):
    if not ref.startswith('http'):
        assert (ROOT/unquote(ref)).is_file(), ref
ids=set(re.findall(r'id="([^"]+)"',html))
assert all(anchor in ids for anchor in re.findall(r'href="#([^"]+)"',html))
assert 'Lorem ipsum' not in html and 'Book a Demo' not in html
assert html.count('<h1 ') == 1 and html.count('<details>') == 8
assert html.count(FORM) >= 4
print('Site gerado. Links locais, imagens, formulário e oito respostas do FAQ verificados.')
